export const actionTypes = {
  SET_MAP_POSITION: "SET_MAP_POSITION",
  SET_COMPANY: "SET_COMPANY",
  SET_TYPE: "SET_TYPE",
  SET_PROJECT: "SET_PROJECT",
  SET_ALERT: "SET_ALERT",
  SET_FORM_ADDRESS_MAP: "SET_FORM_ADDRESS_MAP",
  SET_IMPORT_RESIDE: "SET_IMPORT_RESIDE",
  SET_ACTIVEPAGE: "SET_ACTIVEPAGE",
  SET_MAP_SENSOR: "SET_MAP_SENSOR",
};
